version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env.example
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: podzorovmihail/kittygram_backend
    env_file: .env.example
    volumes:
      - static_volume:/backend_static
      - media_volume:/backend_media
    expose:
      - "8000"

  frontend:
    image: podzorovmihail/kittygram_frontend
    env_file: .env.example
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static

  gateway:
    image: podzorovmihail/kittygram_gateway
    env_file: .env.example
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/mediafiles/
    ports:
      - 9000:80
