version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env.example
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    build: ./backend/
    env_file: .env.example
    volumes:
      - static:/backend_static
      - media:/backend_media
    expose:
      - "8000"

  frontend:
    build: ./frontend/
    env_file: .env.example

  gateway:
    build: ./nginx/
    volumes:
      - static:/staticfiles/
      - media:/mediafiles/
    ports:
      - 9000:80
