version: '3'

volumes:
  pg_data:
  static:
  media:


services:
  db:
    image: postgres:13.10
    env_file: .env.example
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: podzorovmihail/kittygram_backend
    env_file: .env.example
    volumes:
      - static:/backend_static
      - media:/backend_media
    expose:
      - "8000"
  frontend:
    image: podzorovmihail/kittygram_frontend
    env_file: .env.example

  gateway:
    image: podzorovmihail/kittygram_gateway
    volumes:
      - static:/staticfiles/
      - media:/mediafiles/
    ports:
      - 9000:80